### ISSUE TITLE
New release just out

### ISSUE THREAD

**Issue by Ten0** [NuclearPowered/Mappings#4]
Weeelll, here goes. New release just came out (`2021.2.21`).
You might want to wait and see if they release a quick patch though, because as far as I'm concerned, I can't create online rooms anymore with the new version: "Create Game" results in a black screen.

**Comment by Ten0** [comment]
Yup, they quickly patched it: "2021.2.21s"

**Comment by js6pak** [comment]
https://github.com/NuclearPowered/Mappings/releases
